resources:
- repo: self

queue:
  demands: msbuild

trigger:
- master

variables:
  BuildConfiguration: 'Debug'
  PushNupkg: 'False'
  TeamName: 'Package Experience'

steps:
- template: build/build.yml
  parameters:
    nuspecProperties: 'VersionSuffix=-CI-$(Build.BuildNumber)'
