resources:
- repo: self

# queue:
#   demands: msbuild

pool:
  vmImage: windows-2019

trigger:
- core3-preview5

variables:
  BuildConfiguration: 'Debug'
  PushNupkg: 'False'
  TeamName: 'Package Experience'

steps:
- template: build/build.yml
  parameters:
    nuspecProperties: 'VersionSuffix=-CI-$(Build.BuildNumber)'
